config/routes.rb
Fastdash::Application.routes.draw do
  resources :connections
  resources :connection_table_columns
  resources :connection_tables

  get "dashboard/index"
  get "query/index"
  get 'dashboard' => 'dashboard#index'

  root 'dashboard#index'
  

end

app/models/connection.rb
class Connection < ActiveRecord::Base
  validates :adapter, :host, :username, :password, :database, presence: true
  validate :check_adapter
  has_many :connection_tables, :dependent => :destroy

  SUPPORTED_ADAPTERS = %w(mysql postgresql)

  def connection_info
    {
      :adapter  => adapter,
      :host     => host,
      :username => username,
      :password => password,
      :database => database
    }
  end

  private
    def check_adapter
      unless SUPPORTED_ADAPTERS.include? self.adapter
        errors[:base] << "The selected adapter is not supported"
      end
    end
end

app/models/connection_table.rb
class ConnectionTable < ActiveRecord::Base
  belongs_to :connection
  has_many :connection_table_columns, :dependent => :destroy
end

app/controllers/connections_controller.rb
class ConnectionsController < ApplicationController
  before_action :set_connection, only: [:show, :edit, :update, :destroy]

  # GET /connections
  # GET /connections.json
  def index
    @connections = Connection.all
  end

  # GET /connections/1
  # GET /connections/1.json
  def show
  end

  # GET /connections/new
  def new
    @connection = Connection.new
  end

  # GET /connections/1/edit
  def edit
  end

  # POST /connections
  # POST /connections.json
  def create
    @connection = Connection.new(connection_params)

    respond_to do |format|
      if @connection.save
        build_schema(@connection)
        format.html { redirect_to @connection, notice: 'Connection was successfully created.' }
        format.json { render action: 'show', status: :created, location: @connection }
      else
        format.html { render action: 'new' }
        format.json { render json: @connection.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /connections/1
  # PATCH/PUT /connections/1.json
  def update
    respond_to do |format|
      if @connection.update(connection_params)
        build_schema(@connection)
        format.html { redirect_to @connection, notice: 'Connection was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @connection.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /connections/1
  # DELETE /connections/1.json
  def destroy
    @connection.destroy
    respond_to do |format|
      format.html { redirect_to connections_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_connection
      @connection = Connection.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def connection_params
      params.require(:connection).permit(:adapter, :host, :port, :socket, :username, :password, :database, :encoding)
    end

    def build_schema(connection)
      link = Link.establish_connection(connection.connection_info)
      tables = link.connection.tables
      connection.connection_tables.delete_all
      tables.each do |table|
        newTable = connection.connection_tables.build(:alias=>table, :tablename=>table, :display=>true)
        newTable.save

        newTableColumns = link.connection.columns(table)
        newTableColumns.each do |column|

          # t.string   "alias"
          # t.string   "columnname"
          # t.string   "columntype"
          # t.string   "grouping"
          # t.string   "foreignkey"
          # t.boolean  "display"
          # t.integer  "connection_table_id"
          # t.datetime "created_at"
          # t.datetime "updated_at"
          # t.boolean  "null"
          newColumn = newTable.connection_table_columns.build(
            :alias => column.name,
            :columnname => column.name,
            :columntype => column.sql_type,
            :grouping => "Dimension",
            :foreignkey => nil,
            :display => true,
            :null => column.null)
          newColumn.save
        end
      end
    end
end

app/helpers/connections_helper.rb
module ConnectionsHelper
end

app/views/connections/_form.html.erb
<%= simple_form_for(@connection) do |f| %>
  <% if @connection.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@connection.errors.count, "error") %> prohibited this connection from being saved:</h2>

      <ul>
      <% @connection.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%#
      Once this project gets bigger, going to have to pass in the collection as a variable, because this
      isn't sustainable
  %>
  <%= f.input :adapter, collection: [['MySql', 'mysql'], ['Postgres', 'postgresql']], label: 'Adapter' %>
  <%= f.input :host, label: 'Host' %>
  <%= f.input :port, label: 'Port' %>
  <%= f.input :socket, label: 'Socket' %>
  <%= f.input :username, label: 'Username' %>
  <%= f.input :password, label: 'Password' %>
  <%= f.input :database, label: 'Database' %>
  <%= f.input :encoding, label: 'Encoding' %>
  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.button :submit %>
    </div>
  </div>
<% end %>

app/views/connections/edit.html.erb
<h1>Editing connection</h1>

<%= render 'form' %>

<%= link_to 'Show', @connection %> |
<%= link_to 'Back', connections_path %>

app/views/connections/index.html.erb
<h2>Current Connections</h2>
<table class="table table-hover connection-table">
  <thead>
    <tr>
      <th>Host</th>
      <th>Port</th>
      <th>Socket</th>
      <th>Username</th>
      <th>Password</th>
      <th>Database</th>
      <th>Encoding</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @connections.each do |connection| %>
      <tr data-url="<%= connection_path(connection) %>">
        <td><%= connection.host %></td>
        <td><%= connection.port %></td>
        <td><%= connection.socket %></td>
        <td><%= connection.username %></td>
        <td><%= connection.password %></td>
        <td><%= connection.database %></td>
        <td><%= connection.encoding %></td>
        <td><a href="<%= edit_connection_path(connection) %>">Edit</a></td>
        <td><%= link_to 'Delete', connection, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<a href="<%= new_connection_path %>" class="btn btn-default">New Connection</a>

app/views/connections/new.html.erb
<div class="container">
  <div class="col-lg-8">
    <div class="page-header">
      <h3>New connection</h3>
    </div>
    <%= render 'form' %>
  </div>
</div>

<a href="<%= connections_path %>" class="btn btn-link"><span class="glyphicon glyphicon-arrow-left"></span> Back</a>

app/views/connections/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <% if @connection.host.to_s.length > 0 %>
    <div class="row connection-row">
      <div class="col-lg-2 text-right"><strong>Host:</strong></div>
      <div class="col-lg-10"><%= @connection.host %></div>
    </div>
  <% end %>

  <% if @connection.port.to_s.length > 0 %>
    <div class="row connection-row">
      <div class="col-lg-2 text-right"><strong>Port:</strong></div>
      <div class="col-lg-10"><%= @connection.port %></div>
    </div>
  <% end %>

  <% if @connection.socket.to_s.length > 0 %>
    <div class="row connection-row">
      <div class="col-lg-2 text-right"><strong>Socket:</strong></div>
      <div class="col-lg-10"><%= @connection.socket %></div>
    </div>
  <% end %>
  <% if @connection.username.to_s.length > 0 %>
    <div class="row connection-row">
      <div class="col-lg-2 text-right"><strong>Username:</strong></div>
      <div class="col-lg-10"><%= @connection.username %></div>
    </div>
  <% end %>

  <% if @connection.password.to_s.length > 0 %>
    <div class="row connection-row">
      <div class="col-lg-2 text-right"><strong>Password:</strong></div>
      <div class="col-lg-10"><%= @connection.password %></div>
    </div>
  <% end %>

  <% if @connection.database.to_s.length > 0 %>
    <div class="row connection-row">
      <div class="col-lg-2 text-right"><strong>Database:</strong></div>
      <div class="col-lg-10"><%= @connection.database %></div>
    </div>
  <% end %>

  <% if @connection.encoding.to_s.length > 0 %>
    <div class="row connection-row">
      <div class="col-lg-2 text-right"><strong>Encoding:</strong></div>
      <div class="col-lg-10"><%= @connection.encoding %></div>
    </div>
  <% end %>

  <%= link_to 'Edit', edit_connection_path(@connection) %> |
  <%= link_to 'Back', connections_path %>
</div>