config/routes.rb
Fastdash::Application.routes.draw do
  resources :connections
  resources :connection_table_columns
  resources :connection_tables

  get "dashboard/index"
  get "query/index"
  get 'dashboard' => 'dashboard#index'

  root 'dashboard#index'
  

end

app/models/connection_table_column.rb
class ConnectionTableColumn < ActiveRecord::Base
  belongs_to :connection_table
end

app/controllers/connection_table_columns_controller.rb
class ConnectionTableColumnsController < ApplicationController
  before_action :set_connection_table_column, only: [:show, :edit, :update, :destroy]

  # GET /connection_table_columns
  # GET /connection_table_columns.json
  def index
    @connection_table_columns = ConnectionTableColumn.all
  end

  # GET /connection_table_columns/1
  # GET /connection_table_columns/1.json
  def show
  end

  # GET /connection_table_columns/new
  # def new
  #   @connection_table_column = ConnectionTableColumn.new
  # end

  # GET /connection_table_columns/1/edit
  def edit
  end

  # POST /connection_table_columns
  # POST /connection_table_columns.json
  def create
    @connection_table_column = ConnectionTableColumn.new(connection_table_column_params)

    respond_to do |format|
      if @connection_table_column.save
        format.html { redirect_to @connection_table_column, notice: 'Connection table column was successfully created.' }
        format.json { render action: 'show', status: :created, location: @connection_table_column }
      else
        format.html { render action: 'new' }
        format.json { render json: @connection_table_column.errors, status: :unprocessable_entity }
      end
    end

  end

  # PATCH/PUT /connection_table_columns/1
  # PATCH/PUT /connection_table_columns/1.json
  def update
    respond_to do |format|
      if @connection_table_column.update(connection_table_column_params)
        format.html { redirect_to @connection_table_column, notice: 'Connection table column was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @connection_table_column.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /connection_table_columns/1
  # DELETE /connection_table_columns/1.json
  def destroy
    @connection_table_column.destroy
    respond_to do |format|
      format.html { redirect_to connection_table_columns_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_connection_table_column
      @connection_table_column = ConnectionTableColumn.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def connection_table_column_params
      params.require(:connection_table_column).permit(:alias, :columnname, :type, :grouping, :foreignkey, :display, :connection_table_id)
    end
end

app/helpers/connection_table_columns_helper.rb
module ConnectionTableColumnsHelper
end

app/views/connection_table_columns/_form.html.erb
<%= form_for(@connection_table_column) do |f| %>
  <% if @connection_table_column.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@connection_table_column.errors.count, "error") %> prohibited this connection_table_column from being saved:</h2>

      <ul>
      <% @connection_table_column.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :alias %><br>
    <%= f.text_field :alias %>
  </div>
  <div class="field">
    <%= f.label :columnname %><br>
    <%= f.text_field :columnname %>
  </div>
  <div class="field">
    <%= f.label :type %><br>
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :grouping %><br>
    <%= f.text_field :grouping %>
  </div>
  <div class="field">
    <%= f.label :foreignkey %><br>
    <%= f.text_field :foreignkey %>
  </div>
  <div class="field">
    <%= f.label :display %><br>
    <%= f.check_box :display %>
  </div>
  <div class="field">
    <%= f.label :connection_table %><br>
    <%= f.text_field :connection_table %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/connection_table_columns/edit.html.erb
<h1>Editing connection_table_column</h1>

<%= render 'form' %>

<%= link_to 'Show', @connection_table_column %> |
<%= link_to 'Back', connection_table_columns_path %>

app/views/connection_table_columns/index.html.erb
<h1>Listing connection_table_columns</h1>

<table>
  <thead>
    <tr>
      <th>Alias</th>
      <th>Columnname</th>
      <th>Type</th>
      <th>Grouping</th>
      <th>Foreignkey</th>
      <th>Display</th>
      <th>Null</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @connection_table_columns.each do |connection_table_column| %>
      <tr>
        <td><%= connection_table_column.alias %></td>
        <td><%= connection_table_column.columnname %></td>
        <td><%= connection_table_column.columntype %></td>
        <td><%= connection_table_column.grouping %></td>
        <td><%= connection_table_column.foreignkey %></td>
        <td><%= connection_table_column.display %></td>
        <td><%= connection_table_column.null %></td>
        <td><%= link_to 'Show', connection_table_column %></td>
        <td><%= link_to 'Edit', edit_connection_table_column_path(connection_table_column) %></td>
        <td><%= link_to 'Destroy', connection_table_column, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Connection table column', new_connection_table_column_path %>

app/views/connection_table_columns/new.html.erb
<h1>New connection_table_column</h1>

<%= render 'form' %>

<%= link_to 'Back', connection_table_columns_path %>

app/views/connection_table_columns/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Alias:</strong>
  <%= @connection_table_column.alias %>
</p>

<p>
  <strong>Columnname:</strong>
  <%= @connection_table_column.columnname %>
</p>

<p>
  <strong>Type:</strong>
  <%= @connection_table_column.columntype %>
</p>

<p>
  <strong>Grouping:</strong>
  <%= @connection_table_column.grouping %>
</p>

<p>
  <strong>Foreignkey:</strong>
  <%= @connection_table_column.foreignkey %>
</p>

<p>
  <strong>Display:</strong>
  <%= @connection_table_column.display %>
</p>

<p>
  <strong>Connection table:</strong>
  <%= @connection_table_column.connection_table %>
</p>

<%= link_to 'Edit', edit_connection_table_column_path(@connection_table_column) %> |
<%= link_to 'Back', connection_table_columns_path %>