config/routes.rb
Fastdash::Application.routes.draw do
  resources :connections
  resources :connection_table_columns
  resources :connection_tables

  get "dashboard/index"
  get "query/index"
  get 'dashboard' => 'dashboard#index'

  root 'dashboard#index'
  

end

app/controllers/connection_tables_controller.rb
class ConnectionTablesController < ApplicationController
  before_action :set_connection_table, only: [:show, :edit, :update, :destroy]

  # GET /connection_tables
  # GET /connection_tables.json
  def index
    @connection_tables = ConnectionTable.all
  end

  # GET /connection_tables/1
  # GET /connection_tables/1.json
  def show
  end

  # GET /connection_tables/new
  # def new
  #   @connection_table = ConnectionTable.new
  # end

  # GET /connection_tables/1/edit
  def edit
  end

  # POST /connection_tables
  # POST /connection_tables.json
  def create
    @connection_table = ConnectionTable.new(connection_table_params)

    respond_to do |format|
      if @connection_table.save
        format.html { redirect_to @connection_table, notice: 'Connection table was successfully created.' }
        format.json { render action: 'show', status: :created, location: @connection_table }
      else
        format.html { render action: 'new' }
        format.json { render json: @connection_table.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /connection_tables/1
  # PATCH/PUT /connection_tables/1.json
  def update
    respond_to do |format|
      if @connection_table.update(connection_table_params)
        format.html { redirect_to @connection_table, notice: 'Connection table was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @connection_table.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /connection_tables/1
  # DELETE /connection_tables/1.json
  def destroy
    @connection_table.destroy
    respond_to do |format|
      format.html { redirect_to connection_tables_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_connection_table
      @connection_table = ConnectionTable.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def connection_table_params
      params.require(:connection_table).permit(:alias, :tablename, :display, :connection_id)
    end
end

app/helpers/connection_tables_helper.rb
module ConnectionTablesHelper
end

app/views/connection_tables/_form.html.erb
<%= form_for(@connection_table) do |f| %>
  <% if @connection_table.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@connection_table.errors.count, "error") %> prohibited this connection_table from being saved:</h2>

      <ul>
      <% @connection_table.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :alias %><br>
    <%= f.text_field :alias %>
  </div>
  <div class="field">
    <%= f.label :tablename %><br>
    <%= f.text_field :tablename %>
  </div>
  <div class="field">
    <%= f.label :display %><br>
    <%= f.check_box :display %>
  </div>
  <div class="field">
    <%= f.label :connection %><br>
    <%= f.text_field :connection %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/connection_tables/edit.html.erb
<h1>Editing connection_table</h1>

<%= render 'form' %>

<%= link_to 'Show', @connection_table %> |
<%= link_to 'Back', connection_tables_path %>

app/views/connection_tables/index.html.erb
<h1>Listing connection_tables</h1>

<table>
  <thead>
    <tr>
      <th>Alias</th>
      <th>Tablename</th>
      <th>Display</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @connection_tables.each do |connection_table| %>
      <tr>
        <td><%= connection_table.alias %></td>
        <td><%= connection_table.tablename %></td>
        <td><%= connection_table.display %></td>
        <td><%= link_to 'Show', connection_table %></td>
        <td><%= link_to 'Edit', edit_connection_table_path(connection_table) %></td>
        <td><%= link_to 'Destroy', connection_table, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Connection table', new_connection_table_path %>

app/views/connection_tables/new.html.erb
<h1>New connection_table</h1>

<%= render 'form' %>

<%= link_to 'Back', connection_tables_path %>

app/views/connection_tables/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Alias:</strong>
  <%= @connection_table.alias %>
</p>

<p>
  <strong>Tablename:</strong>
  <%= @connection_table.tablename %>
</p>

<p>
  <strong>Display:</strong>
  <%= @connection_table.display %>
</p>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Alias</th>
      <th>Name</th>
      <th>Type</th>
    </tr>
  </thead>
  <tbody>
    <% @connection_table.connection_table_columns.each do |column| %>
      <tr>
        <td><%= column.alias %></td>
        <td><%= column.columnname %></td>
        <td><%= column.columntype %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Back', connection_tables_path %>